name: Pull Request Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
        cache: npm
    - name: NPM Install
      run: npm install
    - name: Setup cloudformation lint
      uses: ScottBrenner/cfn-lint-action@v2
    - name: Run cloudformation lint
      run: cfn-lint -t stack.yaml
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DESIGN_DEPLOYER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DESIGN_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: npm
      - name: Swift Run
        run: swift run
      - name: NPM Install
        run: npm install
      - name: NPM Build
        run: npm run build
      - name: Create S3 Bucket
        run: |
            if aws s3api head-bucket --bucket vapor-design-pull-pr${{github.event.number}} 2>/dev/null; then
              echo "Bucket already exists"
            else
              aws s3 mb s3://vapor-design-pull-pr${{github.event.number}}
              aws s3api delete-public-access-block --bucket vapor-design-pull-pr${{github.event.number}}
              aws s3api delete-bucket-ownership-controls --bucket vapor-design-pull-pr${{github.event.number}}
              aws s3api put-bucket-website --bucket vapor-design-pull-pr${{github.event.number}}  \
                --website-configuration '{"IndexDocument":{"Suffix":"index.html"},"ErrorDocument":{"Key":"404.html"}}'
            fi
      - name: Deploy S3 Website
        uses: danburtenshaw/s3-website-pr-action@v2
        if: ${{ github.event.pull_request.head.repo.full_name == 'vapor/design' && github.actor != 'dependabot[bot]' }}
        with:
          bucket-prefix: "vapor-design-pulls"
          folder-to-copy: "./Output"
