name: PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Node 
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm
      - name: Set up CloudFormation Lint
        uses: ScottBrenner/cfn-lint-action@v2
      - name: Run CloudFormation Lint
        run: cfn-lint -t stack.yml
      - name: Build Publish website
        run: swift run
      - name: Install dependencies
        run: npm install
      - name: Build Node website
        run: npm run build
      - name: Deploy S3 Website
        if: ${{ github.event.pull_request.head.repo.full_name == 'vapor/design' && github.actor != 'dependabot[bot]' }}
        uses: brokenhandsio/s3-website-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DESIGN_DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DESIGN_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
        with:
          bucket-prefix: "vapor-design-pulls"
          folder-to-copy: "./Output"
          bucket-region: "us-east-1"
