name: Pull Request Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: npm
      - name: NPM Install
        run: npm install
      - name: Setup cloudformation lint
        uses: ScottBrenner/cfn-lint-action@v2
      - name: Run cloudformation lint
        run: cfn-lint -t stack.yaml
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DESIGN_DEPLOYER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DESIGN_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: npm
      - name: Swift Run
        run: swift run
      - name: NPM Install
        run: npm install
      - name: NPM Build
        run: npm run build
      - name: Deploy S3 Website
        uses: danburtenshaw/s3-website-pr-action@v2
        if: ${{ github.event.pull_request.head.repo.full_name == 'vapor/design' }}
        with:
          bucket-prefix: "vapor-design-pulls"
          folder-to-copy: "./Output"
