name: Build and deploy design.vapor.codes

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
    - name: Build site
      run: swift run && npm ci && npm run build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
        aws-region: ${{ vars.OIDC_ROLE_REGION }}
    - name: Deploy to AWS Cloudformation
      uses: aws-actions/aws-cloudformation-github-deploy@v2
      env:
        AWS_REGION: 'eu-west-2'
      with:
        name: vapor-design-stack
        template: stack.yml
        parameter-overrides: >-
          DomainName=design.vapor.codes,
          S3BucketName=vapor-design-site,
          AcmCertificateArn=${{ secrets.CERTIFICATE_ARN }}
    - name: Deploy to S3
      env:
        S3_BUCKET_URL: ${{ secrets.VAPOR_API_DOCS_S3_BUCKET_URL }}
        AWS_REGION: 'eu-west-2'
      run: |
        aws s3 sync ./Output s3://vapor-design-site --no-progress --acl public-read
    - name: Invalidate CloudFront
      env:
        DISTRIBUTION_ID: ${{ secrets.VAPOR_DESIGN_DISTRIBUTION_ID }}
        AWS_REGION: 'eu-west-2'
      run: |
        aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths ${INPUT_INVALIDATE_PATHS}
