name: Build and deploy design.vapor.codes

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
    - name: Build site
      run: swift run && npm ci && npm run build
    - name: Configure AWS credentials
      id: cred
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
        aws-region: ${{ vars.OIDC_ROLE_REGION }}
    - name: Deploy to AWS Cloudformation
      id: clouddeploy
      uses: aws-actions/aws-cloudformation-github-deploy@v2
      env:
        AWS_REGION: 'eu-west-2'
      with:
        name: vapor-design-stack
        template: stack.yml
        parameter-overrides: >-
          DomainName=design.vapor.codes,
          S3BucketName=vapor-design-site,
          AcmCertificateArn=${{ secrets.CERTIFICATE_ARN }}
      if: steps.cred.outcome == 'success'
    - name: Deploy to S3
      run: >
        aws s3 sync
        ./Output
        s3://vapor-design-site/
        --acl public-read --follow-symlinks --delete
      env:
        AWS_REGION: 'eu-west-2'
      if: steps.clouddeploy.outcome == 'success'
    - name: Invalidate CloudFront
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/*'
        AWS_REGION: 'eu-west-2'
        DISTRIBUTION_ID: ${{ secrets.VAPOR_DESIGN_DISTRIBUTION_ID }}
